//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PiClimate.Monitor.WebAssembly.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PiClimate.Monitor.WebAssembly.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorizing....
        /// </summary>
        public static string App_AuthorizingNotice {
            get {
                return ResourceManager.GetString("App_AuthorizingNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to see this page..
        /// </summary>
        public static string App_NotAuthorizedNotice {
            get {
                return ResourceManager.GetString("App_NotAuthorizedNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing at this address..
        /// </summary>
        public static string App_RouteNotFoundWarning {
            get {
                return ResourceManager.GetString("App_RouteNotFoundWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Maxim Yudin &lt;stibiu@yandex.ru&gt;.
        /// </summary>
        public static string AppFooter_CreatedByNotice {
            get {
                return ResourceManager.GetString("AppFooter_CreatedByNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Egiraht/PiClimate.
        /// </summary>
        public static string AppFooter_RepositoryLink {
            get {
                return ResourceManager.GetString("AppFooter_RepositoryLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string AppFooter_RepositoryName {
            get {
                return ResourceManager.GetString("AppFooter_RepositoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user name is provided..
        /// </summary>
        public static string AuthPanel_NoUserNameNotice {
            get {
                return ResourceManager.GetString("AuthPanel_NoUserNameNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sign in: {0}.
        /// </summary>
        public static string AuthPanel_SignInFailureF {
            get {
                return ResourceManager.GetString("AuthPanel_SignInFailureF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to proceed to the page..
        /// </summary>
        public static string AuthPanel_SignInRequiredNotice {
            get {
                return ResourceManager.GetString("AuthPanel_SignInRequiredNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no user matching the provided name and password..
        /// </summary>
        public static string AuthPanel_WrongUserNameOrPasswordWarning {
            get {
                return ResourceManager.GetString("AuthPanel_WrongUserNameOrPasswordWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No measurements found for the specified period..
        /// </summary>
        public static string Chart_NoPeriodMeasurementsFoundNotice {
            get {
                return ResourceManager.GetString("Chart_NoPeriodMeasurementsFoundNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the measurements for the specified period..
        /// </summary>
        public static string Chart_PeriodMeasurementsFailureWarning {
            get {
                return ResourceManager.GetString("Chart_PeriodMeasurementsFailureWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Label_Back {
            get {
                return ResourceManager.GetString("Label_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climatic chart.
        /// </summary>
        public static string Label_ClimaticChart {
            get {
                return ResourceManager.GetString("Label_ClimaticChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom period.
        /// </summary>
        public static string Label_CustomPeriod {
            get {
                return ResourceManager.GetString("Label_CustomPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data summary.
        /// </summary>
        public static string Label_DataSummary {
            get {
                return ResourceManager.GetString("Label_DataSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string Label_From {
            get {
                return ResourceManager.GetString("Label_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        public static string Label_Humidity {
            get {
                return ResourceManager.GetString("Label_Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last day.
        /// </summary>
        public static string Label_LastDay {
            get {
                return ResourceManager.GetString("Label_LastDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month.
        /// </summary>
        public static string Label_LastMonth {
            get {
                return ResourceManager.GetString("Label_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week.
        /// </summary>
        public static string Label_LastWeek {
            get {
                return ResourceManager.GetString("Label_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest data.
        /// </summary>
        public static string Label_LatestData {
            get {
                return ResourceManager.GetString("Label_LatestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max humidity.
        /// </summary>
        public static string Label_MaxHumidity {
            get {
                return ResourceManager.GetString("Label_MaxHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max pressure.
        /// </summary>
        public static string Label_MaxPressure {
            get {
                return ResourceManager.GetString("Label_MaxPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max temperature.
        /// </summary>
        public static string Label_MaxTemperature {
            get {
                return ResourceManager.GetString("Label_MaxTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min humidity.
        /// </summary>
        public static string Label_MinHumidity {
            get {
                return ResourceManager.GetString("Label_MinHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min pressure.
        /// </summary>
        public static string Label_MinPressure {
            get {
                return ResourceManager.GetString("Label_MinPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min temperature.
        /// </summary>
        public static string Label_MinTemperature {
            get {
                return ResourceManager.GetString("Label_MinTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period end.
        /// </summary>
        public static string Label_PeriodEnd {
            get {
                return ResourceManager.GetString("Label_PeriodEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period start.
        /// </summary>
        public static string Label_PeriodStart {
            get {
                return ResourceManager.GetString("Label_PeriodStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points displayed.
        /// </summary>
        public static string Label_PointsDisplayed {
            get {
                return ResourceManager.GetString("Label_PointsDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        public static string Label_Pressure {
            get {
                return ResourceManager.GetString("Label_Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Label_RememberMe {
            get {
                return ResourceManager.GetString("Label_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string Label_Resolution {
            get {
                return ResourceManager.GetString("Label_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Label_Show {
            get {
                return ResourceManager.GetString("Label_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Label_SignIn {
            get {
                return ResourceManager.GetString("Label_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string Label_SignOut {
            get {
                return ResourceManager.GetString("Label_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Label_Temperature {
            get {
                return ResourceManager.GetString("Label_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string Label_To {
            get {
                return ResourceManager.GetString("Label_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Label_Update {
            get {
                return ResourceManager.GetString("Label_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Label_User {
            get {
                return ResourceManager.GetString("Label_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in....
        /// </summary>
        public static string NavMenu_SigningInNotice {
            get {
                return ResourceManager.GetString("NavMenu_SigningInNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not signed in..
        /// </summary>
        public static string NavPanel_NotSignedInNotice {
            get {
                return ResourceManager.GetString("NavPanel_NotSignedInNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest measurement has been logged more than {0} ago. The actual data may have changed significantly since then. Check the measurement logger for possible communication failures..
        /// </summary>
        public static string Status_LatestDataExpirationWarningF {
            get {
                return ResourceManager.GetString("Status_LatestDataExpirationWarningF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the latest measurements..
        /// </summary>
        public static string Status_LatestMeasurementsFailureWarning {
            get {
                return ResourceManager.GetString("Status_LatestMeasurementsFailureWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No latest measurements found..
        /// </summary>
        public static string Status_NoLatestMeasurementsFoundNotice {
            get {
                return ResourceManager.GetString("Status_NoLatestMeasurementsFoundNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PiClimate Monitor.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
