//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PiClimate.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PiClimate.Common.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name field is required..
        /// </summary>
        public static string LoginForm_NameIsRequiredNotice {
            get {
                return ResourceManager.GetString("LoginForm_NameIsRequiredNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day(s).
        /// </summary>
        public static string TimePeriods_DayOrDaysF {
            get {
                return ResourceManager.GetString("TimePeriods_DayOrDaysF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hour(s).
        /// </summary>
        public static string TimePeriods_HourOrHoursF {
            get {
                return ResourceManager.GetString("TimePeriods_HourOrHoursF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minute(s).
        /// </summary>
        public static string TimePeriods_MinuteOrMinutesF {
            get {
                return ResourceManager.GetString("TimePeriods_MinuteOrMinutesF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} month(s).
        /// </summary>
        public static string TimePeriods_MonthOrMonthsF {
            get {
                return ResourceManager.GetString("TimePeriods_MonthOrMonthsF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} second(s).
        /// </summary>
        public static string TimePeriods_SecondOrSecondsF {
            get {
                return ResourceManager.GetString("TimePeriods_SecondOrSecondsF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} week(s).
        /// </summary>
        public static string TimePeriods_WeekOrWeeksF {
            get {
                return ResourceManager.GetString("TimePeriods_WeekOrWeeksF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} year(s).
        /// </summary>
        public static string TimePeriods_YearOrYearsF {
            get {
                return ResourceManager.GetString("TimePeriods_YearOrYearsF", resourceCulture);
            }
        }
    }
}
